/** Nombres de evento. Uno por transición: G8 exige que nada ocurra sin evento. */
export const E = {
  CORRIDA_INICIADA: "CORRIDA_INICIADA",
  ADAPTADOR_SELECCIONADO: "ADAPTADOR_SELECCIONADO",

  // Centinela — reloj 1
  UCI_OBSERVACION_LEIDA: "UCI_OBSERVACION_LEIDA",
  CRITERIO_DETECTADO: "CRITERIO_DETECTADO",
  REFERRAL_EMITIDO: "REFERRAL_EMITIDO",
  ESCALAMIENTO_SOLICITADO: "ESCALAMIENTO_SOLICITADO",
  ESCALAMIENTO_RESUELTO: "ESCALAMIENTO_RESUELTO",

  // Caso y órgano
  CASO_TRANSICION: "CASO_TRANSICION",
  AUTORIZACION_OBTENIDA: "AUTORIZACION_OBTENIDA",
  SOPORTE_RETIRADO: "SOPORTE_RETIRADO",
  VENTANA_DCD_EXPIRADA: "VENTANA_DCD_EXPIRADA",
  CROSS_CLAMP: "CROSS_CLAMP",
  ORGANO_TRANSICION: "ORGANO_TRANSICION",
  ALERTA_CIT: "ALERTA_CIT",

  // Despachador
  CAMPANA_ABIERTA: "CAMPANA_ABIERTA",
  CAMPANA_CERRADA: "CAMPANA_CERRADA",
  CONCURRENCIA_CAMBIO: "CONCURRENCIA_CAMBIO",
  AOOS_MARCADO: "AOOS_MARCADO",

  // Carril
  CARRIL_ABIERTO: "CARRIL_ABIERTO",
  CARRIL_OFERTA_ENVIADA: "CARRIL_OFERTA_ENVIADA",
  CARRIL_RESPUESTA_RECIBIDA: "CARRIL_RESPUESTA_RECIBIDA",
  CARRIL_ESTADO: "CARRIL_ESTADO",
  CARRIL_VERIFICACION_INICIADA: "CARRIL_VERIFICACION_INICIADA",
  CARRIL_CAMPO_COMPROMISO: "CARRIL_CAMPO_COMPROMISO",
  CARRIL_COMPROMETIDO: "CARRIL_COMPROMETIDO",
  CARRIL_DEGRADADO: "CARRIL_DEGRADADO",
  CARRIL_RECHAZADO: "CARRIL_RECHAZADO",
  CARRIL_TIMEOUT: "CARRIL_TIMEOUT",
  CARRIL_ABORTADO: "CARRIL_ABORTADO",
  DEGRADACION_PROTEGIO_ISQUEMIA: "DEGRADACION_PROTEGIO_ISQUEMIA",

  // Ruta — reloj 3
  PLAN_TRANSPORTE_SOLICITADO: "PLAN_TRANSPORTE_SOLICITADO",
  PLAN_TRANSPORTE_LISTO: "PLAN_TRANSPORTE_LISTO",

  // Escribano
  EXPEDIENTE_SOLICITADO: "EXPEDIENTE_SOLICITADO",
  EXPEDIENTE_LISTO: "EXPEDIENTE_LISTO",

  // Workspace
  WORKSPACE_ESCRITO: "WORKSPACE_ESCRITO",

  // Línea base serial
  BASELINE_CARRIL_ABIERTO: "BASELINE_CARRIL_ABIERTO",
  BASELINE_CARRIL_CERRADO: "BASELINE_CARRIL_CERRADO",
  BASELINE_TERMINADO: "BASELINE_TERMINADO",

  // Degradación de proveedor (G9)
  DEGRADACION_PROVEEDOR: "DEGRADACION_PROVEEDOR",

  // Caja (§13.4)
  CUSTODIA_TRASPASADA: "CUSTODIA_TRASPASADA",
  SELLO_ALTERADO: "SELLO_ALTERADO",
  TEMPERATURA_FUERA_DE_RANGO: "TEMPERATURA_FUERA_DE_RANGO",
  APERTURA_DENEGADA: "APERTURA_DENEGADA",
  MODO_SIN_RED_ACTIVADO: "MODO_SIN_RED_ACTIVADO",
  MODO_SIN_RED_DESACTIVADO: "MODO_SIN_RED_DESACTIVADO",
} as const;

export type NombreEvento = (typeof E)[keyof typeof E];
