/**
 * §3.2 — taxonomía de códigos de rechazo (sistema OPTN vigente desde dic-2021).
 * Nueve categorías, códigos mutuamente excluyentes.
 */

export const CATEGORIAS_RECHAZO = [
  "DONOR_CANDIDATE_MATCHING",
  "ORGAN_SPECIFIC",
  "CANDIDATE_SPECIFIC",
  "HISTOCOMPATIBILITY",
  "DISEASE_TRANSMISSION_RISK",
  "DONOR_SPECIFIC",
  "LOGISTICS",
  "OTHER",
] as const;

export type CategoriaRechazo = (typeof CATEGORIAS_RECHAZO)[number];

/** Los seis de LOGISTICS son los que el sistema puede atacar directamente. */
export const CODIGOS_LOGISTICS = [
  "LOG_RESOURCE_TIME_CONSTRAINT",
  "LOG_TEAM_OR_FACILITY_UNAVAILABLE",
  "LOG_RECOVERY_TEAM_UNAVAILABLE",
  "LOG_TRANSPORTATION_UNAVAILABLE",
  "LOG_CIT_TOO_LONG",
  "LOG_WIT_TOO_LONG",
] as const;

export const CODIGOS_RECHAZO = [
  // DONOR_CANDIDATE_MATCHING
  "BLOOD_TYPE_INCOMPATIBLE",
  "SIZE_MISMATCH",
  // ORGAN_SPECIFIC
  "ORGAN_SPECIFIC_TEST_RESULTS",
  "ORGAN_ANATOMICAL_DEFECT",
  "BIOPSY_UNACCEPTABLE",
  "ORGAN_PRESERVATION",
  "ORGAN_FUNCTION_ABNORMAL",
  "ORGAN_INJURY",
  "ORGAN_VESSEL_DAMAGE",
  "ORGAN_QUALITY_OTHER",
  // CANDIDATE_SPECIFIC
  "CANDIDATE_UNAVAILABLE",
  "CANDIDATE_MEDICALLY_UNSUITABLE",
  "CANDIDATE_TOO_WELL",
  "CANDIDATE_TOO_SICK",
  "CANDIDATE_REFUSED",
  "CANDIDATE_INFECTION",
  "CANDIDATE_NONCOMPLIANCE",
  "CANDIDATE_INSURANCE",
  "CANDIDATE_OTHER",
  // HISTOCOMPATIBILITY
  "POSITIVE_CROSSMATCH",
  "UNACCEPTABLE_ANTIGEN",
  "HLA_MISMATCH",
  "PRA_TOO_HIGH",
  "HISTOCOMPATIBILITY_OTHER",
  // DISEASE_TRANSMISSION_RISK
  "DONOR_INFECTION_RISK",
  "DONOR_MALIGNANCY_RISK",
  "SEROLOGY_POSITIVE",
  "INCREASED_RISK_BEHAVIOR",
  "DISEASE_TRANSMISSION_OTHER",
  // DONOR_SPECIFIC
  "DONOR_MEDICAL_HISTORY",
  "DONOR_AGE",
  "DONOR_SOCIAL_HISTORY",
  "DONOR_HEMODYNAMIC_INSTABILITY",
  "DONOR_KDPI_TOO_HIGH",
  // LOGISTICS
  ...CODIGOS_LOGISTICS,
  // OTHER
  "OTHER",
  "NO_REASON_GIVEN",
] as const;

export type CodigoRechazo = (typeof CODIGOS_RECHAZO)[number];

export const CATEGORIA_DE: Record<CodigoRechazo, CategoriaRechazo> = {
  BLOOD_TYPE_INCOMPATIBLE: "DONOR_CANDIDATE_MATCHING",
  SIZE_MISMATCH: "DONOR_CANDIDATE_MATCHING",

  ORGAN_SPECIFIC_TEST_RESULTS: "ORGAN_SPECIFIC",
  ORGAN_ANATOMICAL_DEFECT: "ORGAN_SPECIFIC",
  BIOPSY_UNACCEPTABLE: "ORGAN_SPECIFIC",
  ORGAN_PRESERVATION: "ORGAN_SPECIFIC",
  ORGAN_FUNCTION_ABNORMAL: "ORGAN_SPECIFIC",
  ORGAN_INJURY: "ORGAN_SPECIFIC",
  ORGAN_VESSEL_DAMAGE: "ORGAN_SPECIFIC",
  ORGAN_QUALITY_OTHER: "ORGAN_SPECIFIC",

  CANDIDATE_UNAVAILABLE: "CANDIDATE_SPECIFIC",
  CANDIDATE_MEDICALLY_UNSUITABLE: "CANDIDATE_SPECIFIC",
  CANDIDATE_TOO_WELL: "CANDIDATE_SPECIFIC",
  CANDIDATE_TOO_SICK: "CANDIDATE_SPECIFIC",
  CANDIDATE_REFUSED: "CANDIDATE_SPECIFIC",
  CANDIDATE_INFECTION: "CANDIDATE_SPECIFIC",
  CANDIDATE_NONCOMPLIANCE: "CANDIDATE_SPECIFIC",
  CANDIDATE_INSURANCE: "CANDIDATE_SPECIFIC",
  CANDIDATE_OTHER: "CANDIDATE_SPECIFIC",

  POSITIVE_CROSSMATCH: "HISTOCOMPATIBILITY",
  UNACCEPTABLE_ANTIGEN: "HISTOCOMPATIBILITY",
  HLA_MISMATCH: "HISTOCOMPATIBILITY",
  PRA_TOO_HIGH: "HISTOCOMPATIBILITY",
  HISTOCOMPATIBILITY_OTHER: "HISTOCOMPATIBILITY",

  DONOR_INFECTION_RISK: "DISEASE_TRANSMISSION_RISK",
  DONOR_MALIGNANCY_RISK: "DISEASE_TRANSMISSION_RISK",
  SEROLOGY_POSITIVE: "DISEASE_TRANSMISSION_RISK",
  INCREASED_RISK_BEHAVIOR: "DISEASE_TRANSMISSION_RISK",
  DISEASE_TRANSMISSION_OTHER: "DISEASE_TRANSMISSION_RISK",

  DONOR_MEDICAL_HISTORY: "DONOR_SPECIFIC",
  DONOR_AGE: "DONOR_SPECIFIC",
  DONOR_SOCIAL_HISTORY: "DONOR_SPECIFIC",
  DONOR_HEMODYNAMIC_INSTABILITY: "DONOR_SPECIFIC",
  DONOR_KDPI_TOO_HIGH: "DONOR_SPECIFIC",

  LOG_RESOURCE_TIME_CONSTRAINT: "LOGISTICS",
  LOG_TEAM_OR_FACILITY_UNAVAILABLE: "LOGISTICS",
  LOG_RECOVERY_TEAM_UNAVAILABLE: "LOGISTICS",
  LOG_TRANSPORTATION_UNAVAILABLE: "LOGISTICS",
  LOG_CIT_TOO_LONG: "LOGISTICS",
  LOG_WIT_TOO_LONG: "LOGISTICS",

  OTHER: "OTHER",
  NO_REASON_GIVEN: "OTHER",
};

export function esLogistico(codigo: CodigoRechazo): boolean {
  return CATEGORIA_DE[codigo] === "LOGISTICS";
}
